### ISSUE TITLE
"ztoken" fails for SSO

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/zign#21]
`ztoken` will fail if OAuth provider uses SSO and directly redirects back to localhost:

Browser error (localhost server already shut down):
```
This site can’t be reached

localhost refused to connect.
```

**Comment by hjacobs** [comment]
Needs some investigation..

**Comment by hjacobs** [comment]
The reason was simple: one extra request to `favicon.ico`...

**Comment by gargravarr** [comment]
Nice catch!
