### ISSUE TITLE
Informational output should be written to stderr

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/zign#23]
This does not work as expected as the output is cluttered with informational output:

```
tok=$(ztoken)
```

We need to print any debug/info messages to stderr, stdout should only contain the token.

**Comment by hjacobs** [comment]
Hmm, this is not so easy as "Created new window in existing browser session." is generated by the browser call itself (i.e. not Zign nor Python).

**Comment by gargravarr** [comment]
On a Mac, it doesn't happen (using Chrome). On a Linux, shows also for me.
