### ISSUE TITLE
Process stuck in Firefox 

### ISSUE THREAD

**Issue by ZroMnc** [zalando-stups/zign#31]
When doing `ztoken` and firefox set as default browser the process gets stuck and the HTML only shows **Redirecting**.

By the looks of it the include JavaScript does not extract the Token from the URL properly.

```url
http://localhost:8081/#access_token=....
```

in chrome its been casted to

```url 
http://localhost:8081/?access_token=
```

**Comment by ZroMnc** [comment]
Error Consol output:
```
SyntaxError: missing = in const declaration  localhost:8081:18:26
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Comment by prayerslayer** [comment]
Yeah, sorry. Thought it would be okay, will rewrite to ES5 just in case of other browser issues.

**Comment by hjacobs** [comment]
Ah, the new world of EcmaScript 6 is too new :smirk:

**Comment by prayerslayer** [comment]
The bug is marked as "fixed", but apparently not rolled out yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1101653
