### ISSUE TITLE
Why do I see my name/account used for changing labels?

### ISSUE THREAD

**Issue by jbellmann** [zalando-stups/zign#37]
Hi guys,

why do I see my username/account used to change labels for this project. I'm sure not doing anything on the 'zign'-repo. But I see my account to be used to change the labels. Has someone an idea why this happens? Do we use some other tools for issue handling here?

<img width="895" alt="screen shot 2016-12-15 at 23 27 41" src="https://cloud.githubusercontent.com/assets/58709/21244636/d7e9fe5c-c31e-11e6-8b88-7a1984a7df38.png">

<img width="1077" alt="screen shot 2016-12-15 at 23 29 02" src="https://cloud.githubusercontent.com/assets/58709/21244644/e39f800a-c31e-11e6-9661-e99ef40ae914.png">

**Comment by hjacobs** [comment]
@jbellmann check your authorized applications in GitHub, you probably have authorized some 3rd-party app to manage stuff for you.

**Comment by harti2006** [comment]
This is probably waffle.io

**Comment by jbellmann** [comment]
Ok thanks, I will have a look.
