### ISSUE TITLE
--refresh doesn't do anything useful

### ISSUE THREAD

**Issue by musiKk** [zalando-stups/zign#46]
The `--refresh` flag doesn't do anything for named tokens.

```
$ ztoken token --refresh -n postman | md5sum
34e6b2a7a14439271f077690eba31fa3  -
$ ztoken token --refresh -n postman | md5sum
34e6b2a7a14439271f077690eba31fa3  -
```

I expected this to request a new token using the existing refresh token.

Interestingly it also does weird things when requesting an unnamed token (`ztoken token --refresh`). Then a browser window is always opened and after successful authentication you get

```
{
"error": "invalid_client",
"error_description": "invalid client"
}
```

The reason for that seems to be wrong creation of the URL. It points to `.../oauth2/authorize?business_partner_id=True&client_id=ztoken&redirect_uri=http://localhost:8081&response_type=token` (True as business_partner_id).

---

There is also the general weirdness of different behavior of when new tokens are created. Creating an unnamed token just records the refresh token but not the token and no lifetime. This way every run of `ztoken` has to create a new token and so `--refresh` would be pointless there. Creating a named token records the lifetime and seems to return the same token every time as long as it is valid. Even if the `--refresh` thing were fixed, this dichotomy would not go away.

**Comment by hjacobs** [comment]
@musiKk good point, the parameter mapping was wrong and there was no test for it :see_no_evil:

**Comment by hjacobs** [comment]
@musiKk fixed in https://github.com/zalando-stups/zign/releases/tag/1.1.28
