### ISSUE TITLE
No OAuth 2 token endpoint option in ztoken

### ISSUE THREAD

**Issue by gargravarr** [zalando-stups/zign#50]
There is no option available for specifying a different token endpoint, only the authorization endpoint. 

```bash
rreis@tesseract:~/go/src/github.bus.zalan.do/rreis/dcskipper$ ztoken token --help
Usage: ztoken token [OPTIONS]

  Create a new Platform IAM token or use an existing one.

Options:
  -n, --name TOKEN_NAME           Custom token name (will be stored)
  -a, --authorize-url AUTH_URL    OAuth 2 Authorization Endpoint URL to
                                  generate access token
  -c, --client-id CLIENT_ID       Client ID to use
  -p, --business-partner-id PARTNER_ID
                                  Business Partner ID to use
  -r, --refresh                   Force refresh of the access token
  -h, --help                      Show this message and exit.
```

One usecase where this can be useful is in the Sandbox:

```bash
ztoken token -a https://sandbox.identity.zalando.com/oauth2/authorize -t https://sandbox.identity.zalando.com/oauth2/token
```

If only the authorize endpoint is overriden, ztoken still returns a token based on its current configuration, if it sill has a valid refresh token.

To avoid confusion, ztoken should behave:
- If `-a` is specified, ask **always** for the refresh token endpoint
- If `-t` is specified, ask **always** for the authorization endpoint
- When any of the previous options are used, **never** override the existing refresh token from the original configuration.

**Comment by smirnov** [comment]
Can this one be closed? Seems to work on my machine.
