### ISSUE TITLE
webbrowser does not show up when running as root 

### ISSUE THREAD

**Issue by olevchyk** [zalando-stups/zign#57]
I'm running on linux , and `ztoken token ...` does not open web-browser when running from root terminal as it has no connection to my `xhost` 
https://forums.opensuse.org/showthread.php/488901-Python-webbrowser-with-root

**Comment by hjacobs** [comment]
Yes, that's true, but I think this is not an issue we can fix in `zign` --- you should simply not run this CLI tool as `root`.
