### ISSUE TITLE
Command option to allow user to change authentication-provider-url.

### ISSUE THREAD

**Issue by kanuku** [zalando-stups/zign#6]
After specifying the wrong authentication-provider-url I could'nt change the url again.
I had to remove the `zign.yaml` file created on my computer.
Can zign have a command option to set/overwrite current authentication-provider-url?
Something like `zign --set-url https://authentication-provider-url.com/oauth2`

**Comment by hjacobs** [comment]
you can already use:

```
stups configure
```

**Comment by kanuku** [comment]
Thanks
